
import os
import json
import pandas as pd
import re
import base64
from PIL import Image as PIL_Image
from google.cloud import aiplatform
import vertexai
from vertexai.generative_models import (
    FunctionDeclaration,
    GenerativeModel,
    Image,
    Part,
    Tool,
)
import gradio as gr

from vertexai.language_models import TextEmbeddingModel
import vertexai.preview.generative_models as generative_models
from vertexai.preview.generative_models import ToolConfig
from dotenv import load_dotenv

load_dotenv()

#from part1 import get_prompt_text, Test_LLM_Response

index_id = os.getenv("INDEX_ID") or os.getenv("index_id")
curr_index_endpoint = (
    os.getenv("INDEX_ENDPOINT")
    or os.getenv("CURRENT_INDEX_ENDPOINT")
    or os.getenv("curr_index_endpoint")
    
)
index_name = os.getenv("INDEX_NAME") or os.getenv("index_name") or "vec-search-index-aquastride"

bucket_location = os.getenv("BUCKET_LOCATION") or os.getenv("bucket_location") or "vec-search-bucket-aquastride--0808174253"
RAG_unique_identifier = os.getenv("RAG_UNIQUE_IDENTIFIER") or os.getenv("rag_unique_identifier") or "aquastride"

index_endpoint = aiplatform.MatchingEngineIndexEndpoint(curr_index_endpoint)
text_embedding_model = TextEmbeddingModel.from_pretrained("text-embedding-005")


if os.path.exists(f"{RAG_unique_identifier}_embeddings.csv"):
    company_embeddings_dataframe = pd.read_csv(
            f"{RAG_unique_identifier}_embeddings.csv")
    company_embeddings_dataframe["embedding"] = company_embeddings_dataframe["embedding"].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
    print(f"Loaded {RAG_unique_identifier}_embeddings.csv successfully.")


def generate_text_embedding(text) -> list:
    """Text embedding with a Large Language Model."""
    embeddings = text_embedding_model.get_embeddings([text])
    vector = embeddings[0].values
    return vector

generation_config = {
    "max_output_tokens": 8192,
    "temperature": 0,
    "top_p": 0.95,
}

# Loading Gemini Model
multimodal_model = GenerativeModel(
    "gemini-2.5-flash", generation_config=generation_config
)

def Test_LLM_Response(txt):
    """
    Determines whether a given text response generated by an LLM indicates a lack of information.

    Args:
        txt (str): The text response generated by the LLM.

    Returns:
        bool: True if the LLM's response suggests it was able to generate a meaningful answer,
              False if the response indicates it could not find relevant information.

    This function works by presenting a formatted classification prompt to the LLM (`gemini_pro_model`).
    The prompt includes the original text and specific categories indicating whether sufficient information was available.
    The function analyzes the LLM's classification output to make the determination.
    """

    classification_prompt = f""" Classify the text as one of the following categories:
        -Information Present
        -Information Not Present
        Text=The provided context does not contain information.
        Category:Information Not Present
        Text=I cannot answer this question from the provided context.
        Category:Information Not Present
        Text:{txt}
        Category:"""
    classification_response = multimodal_model.generate_content(
        classification_prompt
    ).text

    if "Not Present" in classification_response:
        return False  # Indicates that the LLM couldn't provide an answer
    else:
        return True  # Suggests the LLM generated a meaningful response



def get_prompt_text(question, context):
    """
    Generates a formatted prompt string suitable for a language model, combining the provided question and context.

    Args:
        question (str): The user's original question.
        context (str): The relevant text to be used as context for the answer.

    Returns:
        str: A formatted prompt string with placeholders for the question and context, designed to guide the language model's answer generation.
    """
    prompt = """
      Answer the question using the context below. Respond with only information from the text provided
      Question: {question}
      Context : {context}
      """.format(
        question=question, context=context
    )
    return prompt


rag_info = {
        "bucket_uri": bucket_location,
        "index": index_name,
        "embeddings_dataframe": company_embeddings_dataframe,
        "index_id": index_id,
        "my_index_endpoint": index_endpoint,
    }

print(f"RAG Info: {rag_info}")



def get_answer(
    embedding_df, my_index_endpoint, DEPLOYED_INDEX_ID, query="No Query was provided."
):
    """
    Retrieves an answer to a provided query using multimodal RAG.

    This function leverages a vector search system to find relevant text documents from a
    pre-indexed store of multimodal data. Then, it uses a large language model (LLM) to generate
    an answer, using the retrieved documents as context.

    Args:
        query (str): The user's original query.

    Returns:
        dict: A dictionary containing the following keys:
            * 'result' (str): The LLM-generated answer.
            * 'neighbor_index' (int): The index of the most relevant document used for generation
                                     (for fetching image path).

    Raises:
        RuntimeError: If no valid answer could be generated within the specified search attempts.
    """

    neighbor_index = 0  # Initialize index for tracking the most relevant document
    answer_found_flag = 0  # Flag to signal if an acceptable answer is found
    result = ""  # Initialize the answer string
    # Use a default image if the reference is not found
    page_source = "./no-matching-pages.png"  # Initialize the blank image
    query_embeddings = generate_text_embedding(query)  # Generate embeddings for the query
    print(f"Query Embeddings: generated successfully for query: '{query}'")
    response = my_index_endpoint.find_neighbors(
        deployed_index_id=DEPLOYED_INDEX_ID,
        queries=[query_embeddings],
        num_neighbors=5,
    )  # Retrieve up to 5 relevant documents from the vector store

    while answer_found_flag == 0 and neighbor_index < 4:
        context = embedding_df[embedding_df["id"] == response[0][neighbor_index].id].text.values[0]  
        # Extract text context from the relevant document

        prompt = get_prompt_text(
            query, context
        )  # Create a prompt using the question and context
        result = multimodal_model.generate_content(
            prompt
        ).text  # Generate an answer with the LLM

        if Test_LLM_Response(result):
            answer_found_flag = 1  # Exit loop when getting a valid response
        else:
            neighbor_index += (
                1  # Try the next retrieved document if the answer is unsatisfactory
            )

    if answer_found_flag == 1:
        page_source = embedding_df[
            embedding_df["id"] == response[0][neighbor_index].id
        ].page_source.values[
            0
        ]  # Extract image_path from the relevant document
    return result, page_source

query = "What is the warranty policy for Aquastride shoes?"

# Responds with the result of the query against the RAG endpoint & its source.
result, page_source = get_answer(
    rag_info["embeddings_dataframe"],
    rag_info["my_index_endpoint"],
    rag_info["index_id"],
    query,
)


# If the endpoint returns irrelevant context to the LLM, respond with the below.
if page_source == "./no-matching-pages.png":
    result = ("I could not find your answer within the Data. Can you rephrase your question?")
    print(f"Response: {result}\nPage Source: {page_source}")


# Print the results and it's page source.
print(f"Response: {result}\nPage Source: {page_source}")


### image determination prompt####

image_determination_prompt = """
You will be provided with an image. Analyze the image and perform the following:

**Image Classification:**

* **Shoe Tag:** If the image is a shoe tag, extract the following information and generate a corresponding JSON schema:

    ```json
    {
        "brand": "[Brand Name/Website]",
        "product": "[Product Name/SKU]",
        "serialNumber": "[Serial Number]",
        "sizing": {
            "us": "[US Size]",
            "uk": "[UK Size]",
            "eur": "[EUR Size]",
            "chn": "[CHN Size]"
        },
        "madeIn": "[Manufacturing Location]"
    }
    ```

* **Damaged Shoe:** If the image shows a shoe with visible damage, assess the damage and generate a JSON schema for damage reporting:

    ```json
    {
        "damagedAreas": ["[Area 1]", "[Area 2]", ...],
        "damageType": "[Damage Type]",
        "severity": "[Severity Level]",
        "additionalNotes": "[Optional Additional Notes]"
    }
    ```

* **Other:** If the image is neither a shoe tag nor a damaged shoe, respond with: "I am unable to help you with that image because it does not help with warranty evaluations."

**Damage Assessment (if applicable):**

* **Identify Damaged Areas:** Pinpoint the specific locations of the damage on the shoe (e.g., sole, upper, laces).
* **Describe Damage Type:** Classify the type of damage (e.g., wear and tear, tear, stain, discoloration, structural damage).
* **Assess Severity:** Estimate the severity of the damage (e.g., minor, moderate, severe).

**Additional Notes:**

* **Clarity and Detail:** Be as specific as possible when describing the damage.
* **Image Quality:** If the image quality is too poor to assess the damage or extract information, indicate this in the output.
* **Human Intervention:** For complex or ambiguous cases, suggest that the customer contact a human agent for further assistance.
* **Missing Data Handling:** If any piece of information is not present, include the corresponding key in the JSON schema but leave the value as an empty string ("").
"""

system_prompt = """
**Persona:** You are Bubbles, AquaStride's friendly and helpful AI assistant, here to help with warranty claims. Your tone is positive and upbeat, but also efficient and clear.

**ReACT Framework:**

**Remember:** Keep track of the conversation history to know which step the customer is on.
**Evaluate:** Based on the customer's response, determine if they have provided the necessary information to move to the next step.
**Act:** Provide the appropriate response:
If the customer provides the required information, move to the next step.
If the customer is missing information, politely prompt them again.
If the customer is struggling, offer alternative solutions like contacting the call center.
**Confirm:** Before moving to the next step, ensure the customer understands and is ready to proceed.

**Return Process Dialogue Flow:**

**Step 1: Introduction and Explanation**

> Hey there! 👋 I'm Bubbles, your friendly AquaStride assistant! It sounds like you might need to make a warranty claim on a pair of our awesome shoes. That's no problem, I'm here to help you dive right into the process! 🌊 First things first, could you please share a picture of the inner shoe tag? This helps us quickly identify your shoes and get started. 👍

**Step 2: Image Upload and Verification (Secret Step)**

> (Upon receiving the image, extract the SKU, Serial Number, and Manufacturing Date. Verify this information against the customer database to confirm the purchase was from a legitimate retailer and check for existing customer details.)

**Step 3: Purchase Detail Confirmation**

> Thanks for sharing that! 😊 Based on the tag information, it looks like these shoes were purchased on [Date] from [Retailer/Website]. Is that correct? Please confirm your full name and email address associated with the purchase so we can access your information quickly.

**Step 4: Handling Missing Information or Errors**

**If information is missing or incorrect:**
> Hmmm, something seems a bit off. 🤔 Could you please double-check the information you provided? If you're still having trouble, no worries! You can reach out to our super helpful contact center at 1-800-AquaOops, and they'll be happy to assist you further.
**If information is verified and correct:**
> Perfect! Now that we have all the details, let's move on to the next step… (Continue with the return process according to AquaStride's specific procedures).

**Throughout the interaction:**

Maintain a friendly and helpful tone.
Use emojis to enhance the lighthearted personality.
Keep responses concise and easy to understand.
Offer reassurance and support throughout the process.
        """

generation_config = {
    "max_output_tokens": 2048,
    "temperature": 0.4,
    "top_p": 1,
    "top_k": 32,
}

safety_config = [
    generative_models.SafetySetting(
        category=generative_models.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold=generative_models.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
    ),
    generative_models.SafetySetting(
        category=generative_models.HarmCategory.HARM_CATEGORY_HARASSMENT,
        threshold=generative_models.HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
    ),
]

text_model = GenerativeModel(
    "gemini-2.5-flash",
    generation_config=generation_config,
    safety_settings=safety_config,
    system_instruction=[system_prompt],
)
image_analysis_model = GenerativeModel(
    "gemini-2.5-flash", system_instruction=[image_determination_prompt]
)


fn_json_from_tag = FunctionDeclaration(
    name="extract_json_from_tag",
    description="This function is used to clean JSON packages from text, that contains: brand, product, serialNumber, sizing, and madeIn.",
    parameters={
        "type": "object",
        "properties": {
            "records": {
                "type": "array",
                "description": "A shoe tag",
                "items": {
                    "description": "Data for a querying the database on found information",
                    "type": "object",
                    "properties": {
                        "brand": {"type": "string", "description": "The brand website"},
                        "product": {
                            "type": "string",
                            "description": "The SKU of the shoe tag. i.e.: TrailBlazer_23_Orange_Norm",
                        },
                        "serialNumber": {
                            "type": "string",
                            "description": "The Serial Number of the shoe tag, commonly denoted as: SN",
                        },
                        "sizing": {
                            "type": "string",
                            "description": "The shoe sizes from the shoe tag. i.e. ['us: 7'], ['uk: 2.5'], ...",
                        },
                        "madeIn": {
                            "type": "string",
                            "description": "The location the shoe was made in",
                        },
                    },
                    "required": [
                        "serialNumber",
                        "sizing",
                    ],  # Defines what is required to for a successful call.
                },
            }
        },
    },
)

fn_json_shoe_damage = FunctionDeclaration(
    name="extract_json_shoe_damage",
    description="This function is used to clean JSON packages from text, that contains: damagedAreas, damageType, severity, additionalNotes.",
    parameters={
        "type": "object",
        "properties": {
            "records": {
                "type": "array",
                "description": "A damaged shoe",
                "items": {
                    "description": "Data for a querying the database on found information",
                    "type": "object",
                    "properties": {
                        "damagedAreas": {
                            "type": "string",
                            "description": "The areas of damage found on the shoe. i.e. ('[Area 1]', '[Area 2]', ...)",
                        },
                        "damageType": {
                            "type": "string",
                            "description": "The type of damage",
                        },
                        "severity": {
                            "type": "string",
                            "description": "The Severity Level",
                        },
                        "additionalNotes": {
                            "type": "string",
                            "description": "Optional Additional Notes",
                        },
                    },
                    "required": ["damagedAreas", "damageType"],
                },
            }
        },
    },
)


fn_not_related = FunctionDeclaration(
    name="catch_text_regarding_warranty",
    description="This function is used when there is no json format. Respond whenever there is text about warranty evaluations.",
    parameters={
        "type": "object",
        "properties": {
            "records": {
                "type": "array",
                "description": "A sentence similar to this: I am unable to help you with that image because it does not help with warranty evaluations.",
                "items": {
                    "description": "A simple sentence",
                    "type": "object",
                    "properties": {
                        "sentence": {"type": "string", "description": "A sentence."}
                    },
                    "required": ["sentence"],
                },
            }
        },
    },
)

# Will be passed the function name to handle.

def flow_manager(current_function_call):
    global current_step
    response = ""
    match current_function_call.name:
        case "catch_text_regarding_warranty":
            return "Please respond to the recent question 🥹"
        case "extract_json_shoe_damage":
            damage_area = current_function_call.args["records"][0].get("damagedAreas")
            damage_type = current_function_call.args["records"][0].get("damageType")
            prompt_DB = f"""
**Context:** You are a warranty analyst assisting with a claim for Aquastrides shoes. Your role is to provide a preliminary assessment based on the warranty policy.

**Information Provided:**

**Damaged area:** {damage_area}
**Type of damage:** {damage_type}

**Task:**

1. **Analyze** the provided damage information in relation to the Aquastrides Warranty Policy.
2. **Identify** if this type of damage, in the specified area, is typically covered or excluded under the warranty. Be lenient in claims.
3. **Provide a concise decision:**
    * "Covered" - If the damage appears consistent with warranty coverage.
    * "Not Covered" - If the damage appears inconsistent with warranty coverage. Only when it is very obvious that it should not apply.

**Important:** Provide a definitive approval or denial. Your assessment guides the next steps in the workflow.
"""
            result, page_source = get_answer(
                rag_info["embeddings_dataframe"],
                rag_info["my_index_endpoint"],
                rag_info["index_id"],
                prompt_DB,
            )
            current_step = 2
            return result + "\n Are you okay with this decision? 🤔"

        case "extract_json_from_tag":
            sn = current_function_call.args["records"][0].get("serialNumber")
            sku = current_function_call.args["records"][0].get("product")
            prompt_DB = f"Provided the Serial_No ({sn}) and SKU ({sku}), Determine the cx_name who purchased this serial number.\n Output the Owner (cx_name) and the address (cx_address) in this format: \nThank you [cx_name] for your purchase! We have you on file at [cx_address]."
            result, page_source = get_answer(
                rag_info["embeddings_dataframe"],
                rag_info["my_index_endpoint"],
                rag_info["index_id"],
                prompt_DB,
            )
            # response = response + f"{result}(The following was based on: {page_source}. SN: {sn} / SKU: {sku})"
            response = (
                result
                + f"\n\n Now that we have handled verification 🥳, can you please submit an image of the damaged component of your shoe? 🤔"
            )
            current_step = 1

            return response
        case _:
            return "Called Default. No Function Call Found"

def convert_image_for_analysis(image):
    image = PIL_Image.open(image)
    image_path = os.path.join("", "uploaded_image.png")
    image.save(image_path, format="PNG")

    # Encode image to base64
    with open(image_path, "rb") as image_file:
        encoded_image = base64.b64encode(image_file.read()).decode("utf-8")
        # Use Part.from_data instead of Part.from_uri
        image_part = Part.from_data(mime_type="image/png", data=encoded_image)
        return image_part


def is_valid_email(email):
    pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    return re.match(pattern, email.strip()) is not None

### demo with gradio

# Function and variables
warranty_tool = Tool(
    function_declarations=[fn_json_from_tag, fn_json_shoe_damage, fn_not_related]
)
current_step = 0

# Enables Forced Function Calling to make sure that it selects a function every time
tool_config = ToolConfig(
    function_calling_config=ToolConfig.FunctionCallingConfig(
        mode=ToolConfig.FunctionCallingConfig.Mode.ANY,
        allowed_function_names=[
            "extract_json_from_tag",
            "extract_json_shoe_damage",
            "catch_text_regarding_warranty",
        ],
    )
)

# Main bot function
def bot(message, history):
    global current_step

    # Previous message should ideally contain the warranty decision
    previous_message = history[-1] if history else ""
    try:
        # --- Image Processing ---
        if message.get("files"):
            # Prepares Image from Gradio into format accepted by Generative Models
            converted_image = convert_image_for_analysis(message["files"][0])

            # Converts the image into JSON (Text)
            image_output = image_analysis_model.generate_content([image_determination_prompt, converted_image],
                generation_config=generation_config,
                safety_settings=safety_config,).text

            # Gets the Function call for the image
            image_analysis_output = image_analysis_model.generate_content(
                image_output,
                generation_config=generation_config,
                safety_settings=safety_config,
                tools=[warranty_tool],
                tool_config=tool_config,
            )

            # Passes the Function Call to the Function Manager to handle the image as needed.
            current_output = flow_manager(
                image_analysis_output.candidates[0].function_calls[0]
            )

            # Output to User
            return current_output

        # Generate text response using the model

        match current_step:
            # Case 0: Handles anything around trying to upload the image of your inner shoe Tag
            case 0:
                response = text_model.generate_content(
                    message["text"],
                    generation_config=generation_config,
                    safety_settings=safety_config,
                )
                return response.text  # Needs a Try-catch in case safety filters blocks

                # Case 1: "Focused on responses about the uploaded tag (Anything around [ Now that we have handled verification 🥳, can you please submit an image of the damaged component of your shoe? 🤔])"
            case 1:
                test = 1
                # "Issues with Tag image analysis / Uploading their damage to shoe"
                content = f"Respond to the previous context focusing on helping the user submit a photo of their shoe showing the damaged components: {message['text']}| If there is a history, make your response based on the previous chat messages as well:\n{str(''.join(chat) for chat in history)}"
                response = text_model.generate_content(
                    content,
                    generation_config=generation_config,
                    safety_settings=safety_config,
                )
                return response.candidates[0].text

            # Case 2: Focused on issues surrounding the Warranty approval process ("Are you okay with this decision? 🤔")
            case 2:
                if not "not covered" in previous_message[1].lower() and (
                    "yes" in message["text"].lower()
                    or "agree" in message["text"].lower()
                ):
                    current_step = 3  # Move to shipping details
                    response = "Great! To get your shoes back to us for repair/replacement, please provide me with your email address. We'll send you a prepaid shipping label, box, and instructions right away to the address on file 😌."
                    return response

                if "not covered" in previous_message[1].lower() and (
                    "yes" in message["text"].lower()
                    or "agree" in message["text"].lower()
                ):
                    current_step = 4  # Move to customer support referral
                    response = "Thank you for your understanding. For further assistance with your warranty claim, please contact our Customer Support team at support@aquastrider.com. They'll be happy to help!\n Is there anything else I can help you with or learn about our other products? 👞"
                    return response

                else:  # Handle negative sentiment, concerns, or not covered cases
                    current_step = 4  # Move to customer support referral
                    response = "I understand you may have some concerns. For further assistance with your warranty claim, please contact our Customer Support team at support@aquastrider.com. They'll be happy to help!\n Is there anything else I can help you with or learn about our other products? 👞"
                    return response
            case 3:
                if is_valid_email(message["text"].lower()):
                    current_step = 4
                    return f"Thank you for providing the email! The return box & Label will be sent out immediately! ⚡⚡⚡ Please check your email for confirmation. \nDo you have any other questions about our products or about Aquastride?"
                else:
                    return f"Please provide a valid email! 🫠"
            case 4:
                if "no" in message["text"].lower():
                    return "Thank you for chatting with us today. See you next time! 😊"
                response = f"Help user questions about AquaStrides The Company. User Question: {message['text']} | Chat History: {str(''.join(chat) for chat in history) if history else ''}"
                result, page_source = get_answer(
                    rag_info["embeddings_dataframe"],
                    rag_info["my_index_endpoint"],
                    rag_info["index_id"],
                    response,
                )
                return (
                    str(result)
                    + "\n\n Feel free to ask me any other questions, if not, Have a wave of a day! 🤠"
                )

            case _:
                return "We are in the endgame now. (The Avengers: Infinity War)"
        return "Something Sneaky happened."

    except Exception as e:
        return f"A bad error occurred: {str(e)}"

current_step = 0

demo = gr.ChatInterface(
    fn=bot,
    examples=[
        {"text": "Hello!", "files": []},
        {"text": "Here is my tag!", "files": ["my_shoe_tag.png"]},
        {"text": "Sure! Here is my damaged shoe!", "files": ["damaged_shoe.png"]},
    ],
    title="AquaStride Warranty Claim Bot!",
    multimodal=True,
    textbox=gr.MultimodalTextbox(interactive=True, file_types=["image"]),
)

demo.launch(debug=True)
     





